### ISSUE TITLE
Could not deduce (Control.Monad.IO.Unlift.MonadUnliftIO m)

### ISSUE THREAD

**Issue by Unisay** [cjdev/monad-persist#4]
```
    [1 of 2] Compiling Control.Monad.Persist ( library/Control/Monad/Persist.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/Control/Monad/Persist.o )
    
    /tmp/stack15043/monad-persist-0.0.2.0/library/Control/Monad/Persist.hs:116:31: error:
        • Could not deduce (unliftio-core-0.1.1.0:Control.Monad.IO.Unlift.MonadUnliftIO
                              m)
            arising from a use of ‘runSqlConn’
          from the context: MonadBaseControl IO m
            bound by the type signature for:
                       runSqlPersistT :: forall (m :: * -> *) a.
                                         MonadBaseControl IO m =>
                                         SqlPersistT m a -> SqlBackend -> m a
            at library/Control/Monad/Persist.hs:115:1-79
          Possible fix:
            add (unliftio-core-0.1.1.0:Control.Monad.IO.Unlift.MonadUnliftIO
                   m) to the context of
              the type signature for:
                runSqlPersistT :: forall (m :: * -> *) a.
                                  MonadBaseControl IO m =>
                                  SqlPersistT m a -> SqlBackend -> m a
        • In the expression: runSqlConn m
          In an equation for ‘runSqlPersistT’:
              runSqlPersistT (PersistT m) = runSqlConn m
        |
    116 | runSqlPersistT (PersistT m) = runSqlConn m
        |                               ^^^^^^^^^^^^
    
    /tmp/stack15043/monad-persist-0.0.2.0/library/Control/Monad/Persist.hs:122:35: error:
        • Could not deduce (unliftio-core-0.1.1.0:Control.Monad.IO.Unlift.MonadUnliftIO
                              m)
            arising from a use of ‘runSqlPool’
          from the context: MonadBaseControl IO m
            bound by the type signature for:
                       runSqlPoolPersistT :: forall (m :: * -> *) a.
                                             MonadBaseControl IO m =>
                                             SqlPersistT m a -> ConnectionPool -> m a
            at library/Control/Monad/Persist.hs:121:1-87
          Possible fix:
            add (unliftio-core-0.1.1.0:Control.Monad.IO.Unlift.MonadUnliftIO
                   m) to the context of
              the type signature for:
                runSqlPoolPersistT :: forall (m :: * -> *) a.
                                      MonadBaseControl IO m =>
                                      SqlPersistT m a -> ConnectionPool -> m a
        • In the expression: runSqlPool m
          In an equation for ‘runSqlPoolPersistT’:
              runSqlPoolPersistT (PersistT m) = runSqlPool m
        |
    122 | runSqlPoolPersistT (PersistT m) = runSqlPool m
        |                                   ^^^^^^^^^^^^
    
Type help for available commands. Press enter to force a rebuild.

```

**Comment by docmoxie** [comment]
I've solved this in the 'lts-12.9' branch by just following the compiler hints in your error. That said, I'm not sure I'm totally happy with it--it seems strange to have both MonadBaseControl and MonadUnliftIO, since it's my understanding that they both attempt to do the same sort of thing.

**Comment by lexi-lambda** [comment]
I agree with @docmoxie’s assessment. `MonadBaseControl` and `MonadUnliftIO` are two different approaches to do the same thing. `MonadBaseControl` is significantly more general than `MonadUnliftIO`, since `MonadUnliftIO` basically just restricts you to some transformer stack that’s morally equivalent to `ReaderT IO`, which is pretty limiting. Unfortunately, it appears that persistent has been updated to use `MonadUnliftIO`, which essentially means it has been reduced in capability.

The good news is that it should be possible for `monad-persist` to be made compatible with the new `persistent` API without changing `monad-persist`’s API by specializing `persistent`’s `runSqlPool` to `IO` and using the `control` operator from `monad-control` to lift it into the transformer stack.

**Comment by docmoxie** [comment]
@lexi-lambda, can you elaborate? My understanding is that `control` provides a function that allows a given state-y transformer action (in this case, `ReaderT SqlBackend m a` to get unwrapped, run, and then rewrapped...basically, `lift`ing it into IO. 

So, by specializing `runSqlPool` like so:
```
runSqlPoolIO :: (Sql.IsSqlBackend backend) => ReaderT backend IO a -> Pool backend -> IO a
runSqlPoolIO = runSqlPool
```
We get a function that doesn't rely on the `MonadUnliftIO` constraint, that can be lifted with the aforementioned function `control` provides...but, try as I might, I can't get it to work. Am I at least on the right track, philosophically? I'm expecting the final answer to look something like the following:

```
runSqlPoolPersistT :: (MonadBaseControl IO m) => SqlPersistT m a -> ConnectionPool -> m a
runSqlPoolPersistT (PersistT m) pool = control $ \runInIO -> runSqlPoolIO (runInIO m) pool
```
That is: lift the unwrapped `PersistT` action into IO, then it should be at the right level to be used by `runSqlPoolIO`...but obviously I'm missing something :)

**Comment by docmoxie** [comment]
@lexi-lambda OK, I think I got it after sleeping on it. I kept reading all these articles about using control to lift callbacks into IO, and the revelation was that `runReaderT m` is essentially a callback :: `r -> m a`. That eventually led me to:
```
runSqlPoolPersistT :: (MonadBaseControl IO m, StM m a ~ a) => SqlPersistT m a -> ConnectionPool -> m a
runSqlPoolPersistT (PersistT action) pool = control $ \runInIO -> runSqlPoolIO (mapReaderT runInIO action) pool
```

It appears to typecheck...I don't fully understand yet, but there's a glimmer there. Thanks for being a rubber ducky :)

**Comment by lexi-lambda** [comment]
I looked into a little bit of this today, and it’s much harder than I initially thought. Your solution is clever, but it hints at the problem: the `StM m a ~ a` constraint means that only *stateless* monads can be used, which makes sense, because `MonadUnliftIO` is essentially `MonadBaseControl` restricted to stateless transformers (i.e. only `ReaderT` and `IdentityT`).

I feel like it ought to be possible to, using `monad-control`, write some function with the signature

```haskell
(MonadBaseControl b m, MonadTransControl t, StT t a ~ a) => (forall c. t b c -> b c) -> t m a -> m a
```

where only the transformer at the top of the stack (in this case `ReaderT`) is required to be stateless. Sadly, I have not managed to write a function that implements this type signature, and it may be impossible… I just don’t have an intuition at the moment for *why* it would be impossible.

**Comment by lexi-lambda** [comment]
Aha! I just cracked it, thanks to your use of `mapReaderT`, which reminded me of some information from [my past self](https://lexi-lambda.github.io/blog/2017/04/28/lifts-for-free-making-mtl-typeclasses-derivable/) that I’d forgotten. Specifically, using `MonadTransControl`, one can write this function:

```haskell
mapT :: (Monad m, Monad n, MonadTransControl t, Monad (t n)) => (m (StT t a) -> n (StT t b)) -> t m a -> t n b
mapT f m = liftWith (\run -> f (run m)) >>= restoreT . return
```

This is a generic version of `mapReaderT` that works with any monad transformer that implements `MonadTransControl`. Using that, it’s possible to write a `liftBaseRun` function:

```haskell
liftBaseRun :: forall t m b a. (MonadBaseControl b m, MonadTransControl t, Monad (t b), StT t a ~ a, StT t (StM m a) ~ StM m a) => (forall c. t b c -> b c) -> t m a -> m a
liftBaseRun f m = control $ \runInBase -> f (mapT runInBase m)
```

(In GHC 8.6, the annoying `(StT t a ~ a, StT t (StM m a) ~ StM m a)` constraints should be possible to reduce to `forall c. StT t c ~ c` using the awesome new `QuantifiedConstraints` extension, but for now we have to name the individual cases.)

This `liftBaseRun` function happens to be exactly what’s needed to implement `runSqlPersistT` and `runSqlPoolPersistT` with no loss of generality:

```haskell
runSqlPersistT :: MonadBaseControl IO m => SqlPersistT m a -> SqlBackend -> m a
runSqlPersistT (PersistT m) r = liftBaseRun (flip runSqlConn r) m

runSqlPoolPersistT :: MonadBaseControl IO m => SqlPersistT m a -> ConnectionPool -> m a
runSqlPoolPersistT (PersistT m) r = liftBaseRun (flip runSqlPool r) m
```

As it happens, though, `liftBaseRun` is unnecessarily general in this particular case, since we only need to support `ReaderT`, not arbitrary stateless transformers, so I’ll reduce it to the more specific case to avoid the need for `mapT` and push a fix.
